### ISSUE TITLE
Issue with cask, calling deprecated "stanza"

### ISSUE THREAD

**Issue by zoispag** [dteoh/homebrew-sqa#2]
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the dteoh/sqa tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/dteoh/homebrew-sqa/Casks/slowquitapps.rb:8

**Comment by ak2k** [comment]
Hi @dteoh - Do you have feedback on this pull?
